### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by brainstorm** [neurolabusc/MRIcroGL#1]
I would like to package your software for Homebrew, it would be very nice I you followed http://semver.org guidelines when tagging/releasing over here in GitHub :)

**Comment by brainstorm** [comment]
I know that I can find the code over here:

http://www.mccauslandcenter.sc.edu/CRNL/tools/beta

But I would very much prefer to have it hosted here with consistent and package-friendly versioning in the tarball name, instead of just "source.zip":

http://www.mccauslandcenter.sc.edu/CRNL/sw/mricrogl/source.zip

**Comment by neurolabusc** [comment]
It is all online now. Needed to replace a couple functions that were not open source. Michael Hanke has been able to add this to Debian which should help many Linux users. I personally like distributing the compiled software via NITRC, and am not familiar with the advantages of Homebrew. I would be happy for you to make installation as easy as possible for others.

**Comment by brainstorm** [comment]
Great! Happy to hear that. Could you make a release:

https://help.github.com/articles/creating-releases/

And add this practice to your release engineering process? It'll help packaging systems a lot if you tag the releases using semver:

http://semver.org/

Thanks!

**Comment by neurolabusc** [comment]
Will do, I will make releases at the same time as the NITRC releases. This is a standalone application, not a library, so it does not have an API, so I am less sure regarding the utility of following the semver numbers. The program does have its own internal scripting language, and I think this is pretty mature.

**Comment by brainstorm** [comment]
Semver is a general way of version numbering programs, not only libraries. 

As long as MRIcroGL has a stable (ascending) versioning scheme **as part of the filename** over time it's ok. Otherwise package managers have a hard time distinguising new versions over old ones.

**Comment by neurolabusc** [comment]
Release published (11 Nov 2015 release is semver 1.0.20151111)
