### ISSUE TITLE
How atlas are detected?

### ISSUE THREAD

**Issue by lrq3000** [neurolabusc/MRIcroGL#10]
Hey there,

Not a bug but a question: how does MRIcroGL recognizes atlas in nifti files from normal nifti files?

Indeed, there is no option to force the activation of atlas coloring (coloring each region depending on its integer value), so I guess this is automatically detected from the nifti, but how? What does the nifti file needs to include to be detected as an atlas?

Thank you very much in advance!

**Comment by lrq3000** [comment]
Ah sorry to bother you, I[ found out how](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/group__NIFTI1__INTENT__CODES.html#a26): intent_code (in nifti headers) should be set to 1002.

Thanks anyway!

**Comment by neurolabusc** [comment]
Correct you want to set the [intent_code](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) to specify that the values are labels, not continuous values.

**Comment by lrq3000** [comment]
Thank you very much for the confirmation and the link, I will refer to that now :-)
