### ISSUE TITLE
Error compiling in windows

### ISSUE THREAD

**Issue by kauttoj** [neurolabusc/MRIcroGL#13]
I installed Lazarus, downloaded the latest source and tried running the code on windows 8.1. I got an error:
    Error reading ScriptForm.DesignTimePPI: Unknown property: "DesignTimePPI"
Any idea what's going on here? 

My idea was to increase left-hand panel width in mricrogl (should not be too difficult). Currently the panel is too narrow and makes using overlays very difficult (see figure). In some earlier version there was separate pop-up window for overlays. That was much better.

![mricrogl](https://user-images.githubusercontent.com/17804946/29891683-a5cf1692-8dd4-11e7-8394-212560e0c571.png)

**Comment by neurolabusc** [comment]
You can ignore the error - it simply reflects that I built the project using the latest SVN of Lazarus which includes properties that are not yet used in the stable releases of Lazarus. 

You are correct - the Overlay panel used to be a separate window, but now it is integrated into the main tool panel. The advantages of the new approach is that it works well in full-screen mode, you do not have to find a place for a separate Window, and it is automatically context-dependent (you see the overlay panel whenever overlays are open, and it is hidden when you close overlays). I agree it is a bit of a tight fit on the tool panel. I have tried to design the software to work on 1024x768 screens which does not provide a lot of screen real estate. I will consider making the size of the tool panel dynamic based on the screen width.

In any case, feel free to fork this project - you can have the overlay panel as a separate window or make the tool panel larger. If you develop a better solution than mine you can submit a pull request.
