### ISSUE TITLE
Current HEAD will compile but not run.

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcroGL#14]
Contingent on the famous mandelbug not occurring, I can compile but not execute MRIcroGL (e92f6da35612d2391ce0d41a8aec6e67939cacb6). I get a popup stating:

>Error reading ScriptForm.DesignTimePPI: 
Unknown property: "DesignTimePPI".
Press OK to ignore and risk data corruption.
Press Cancel to kill the program.

From the command line, I get:

```
[FORMS.PP] ExceptionOccurred 
  Sender=EReadError
  Exception=Error reading ScriptForm.DesignTimePPI: Unknown property: "DesignTimePPI"
  Stack trace:
  $00000000004A28D6
  $00000000004A1B99
  $00000000004A35C5
  $00000000004D3F7B
  $00000000004D31A1
  $000000000044B6BD
  $000000000044DE2C
  $0000000000455831
TApplication.HandleException Error reading ScriptForm.DesignTimePPI: Unknown property: "DesignTimePPI"
  Stack trace:
  $00000000004A28D6
  $00000000004A1B99
  $00000000004A35C5
  $00000000004D3F7B
  $00000000004D31A1
  $000000000044B6BD
  $000000000044DE2C
  $0000000000455831
```

**Comment by neurolabusc** [comment]
Sounds like you are using a version of Lazarus that predates HiDPI settings. The easy solution is to upgrade Lazarus to 1.8 RC 4 or the development branch (1.9.0). I do not have old versions of Lazarus available, but if you want to reinstate compatibility with old versions of Lazarus you will probably have to comment out (`//`)the line
`{$IFDEF FPC}{$IFDEF LINUX} HighDPILinux(GetFontData(GLForm1.Font.Reference.Handle).Height); {$ENDIF} {$ENDIF}`
From the file simplelaz.lpr, though this will influence scaling for high resolution images.
