### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by damaggu** [neurolabusc/MRIcroGL#15]
Hi,

I created a zstatistic image and was looking at it in mricrogl and it looks weirdly broken. I wanted to ask, if you could maybe tell me why is that the case? I attached image and screenshot in the following link:
[https://www.dropbox.com/sh/84ybhf2ltx8y9nt/AABi-XyttR-xkDxRABTgBScHa?dl=0](url)
Thanks and best

**Comment by neurolabusc** [comment]
I am afraid I can not replicate your problem on my Mac. You can try launching the program with the 'Shift' key down to see if you can reset your graphics settings. What information do you get when you type `sw_vers` and `system_profiler SPHardwareDataType`? You can get further advice here:
  http://www.mccauslandcenter.sc.edu/mricrogl/troubleshooting


![rat](https://user-images.githubusercontent.com/8930807/32562166-f945333c-c47b-11e7-9f94-6db35fa274cc.jpg)

**Comment by damaggu** [comment]
First of all, thanks a lot for your very quick response. I'm very sorry but I just noticed that I added the wrong scan. I just replaced the fail. Now it should be possible to reproduce the artifact. Thanks again a lot.
[https://www.dropbox.com/sh/84ybhf2ltx8y9nt/AABi-XyttR-xkDxRABTgBScHa?dl=0](url)

**Comment by neurolabusc** [comment]
Hello-
  I am afraid this is a problem with your image, not my software. All tools (SPM, fslview, fsleyes, MRIcroGL, MRIcron, etc) agree that this image is corrupted. The header suggests it was created by "fsl 5.0", so I suggest you check the provenance of this image.

**Comment by neurolabusc** [comment]
Hello-
  I am afraid this is a problem with your image, not my software. All tools (SPM, fslview, fsleyes, MRIcroGL, MRIcron, etc) agree that this image is corrupted. The header suggests it was created by "fsl 5.0", so I suggest you check the provenance of this image.
