### ISSUE TITLE
Color picker for overlays colors

### ISSUE THREAD

**Issue by lrq3000** [neurolabusc/MRIcroGL#18]
Hey there :-)

It would be great to have the ability to choose more colors for overlays, for example by having a color picker for the starting and ending color (or simply a uniform color, that would work as well!). Indeed, particularly when additive is enabled, it can become a bit complicated to display more than 5 overlays at once (as some additive colors will display as another color, eg blue and red will become purple but purple might be assigned to another overlay).

PS: this feature would also be amazing in Surf Ice as well ;)

**Comment by neurolabusc** [comment]
MRIcroGL should provide dozens of color options for overlays (see attached screenshot). You can also create new color look-up table using a text editor and creating a new "*.clut" file into the MRIcroGL "lut". MacOS users will want to "Show Package Contents" with the finder to see the lut folder. The same format works for Surf Ice as well. The example below shows a color scheme that goes from bright blue to bright red with increasing image intensity.

```
[FLT]
min=0
max=0
[INT]
numnodes=2
[BYT]
nodeintensity0=0
nodeintensity1=255
[RGBA255]
nodergba0=0|0|255|0
nodergba1=255|0|0|70
```

I am not sure there is an easy solution for the additive color situation. The human perceptual systems opponent color process means we see wavelengths as additive (e.g. mixing pure red and green appears "orange" and is indistinguishable from a single light source emitting light at the pure orange wavelength). If you want to add more combinations, you could use a tool like photoshop to add different textures to the different overlays, or you could use Matlab to make each overlay image have a different texture. I just do not think there is a way to add this into MRIcroGL without making the interface too complicated.

**Comment by lrq3000** [comment]
Ah great! This should solve my issue, I'll give it a try, thanks a lot for the example :D

About the additive issue, it's only an issue when the number of base colors is limited, but as long as I can create my own (eg, brown, pink, orange, etc) I can tweak my colors so that this won't be an issue anymore :-)

BTW an alternative solution might be to allow to use the atlas palette, by n-arizing the map (I did not think about it before but this would work too!).
