### ISSUE TITLE
Bug: ColorbarSize ignored by Mosaic function

### ISSUE THREAD

**Issue by mzunhammer** [neurolabusc/MRIcroGL#20]
Thank you for the additional colorbar-options in the last update of MRIcroGL.
I've noticed a bug when setting the Font/Colorbar size in Preferences > Advanced.
After editing MRIcroGL.ini (e.g. by changing  ColorbarSize=0.03500000015 to
ColorbarSize=0.01500000015) the colorbar is resized for all display options, with the exception of  MOSAIC, which ignores the ColorbarSize (regardless of whether the GUI or the script is used).
Generally, a function to flexibly change ColorbarSize or Font sizes in Scripting would be awesome.
Cheers, Matthias

**Comment by neurolabusc** [comment]
The pre-release  [v1.0.20180402(https://github.com/neurolabusc/MRIcroGL/releases/tag/v1.0.20180402) adjusts this - I have uploaded a MacOS compiled version, for Linux or Windows you can build your own or wait a few days. This new release includes the scripting function COLORBARSIZE, so the code `colorbarsize(0.05);` will attempt to find a nice colorbar size that is about 5% of the image dimension. This now also impacts the mosaic views. 

Note you can not specify the font size, but it does scale with the colorbar size. The font size is dependent on your colorbar range, with a colorbar that has the range -1024..1024 requiring a smaller font that a color bar with the range 1..4 to display the precision. In general, you may want to use PhotoShop or another image editor to precisely tune your font.

Also note that mosaics are very different from the other views. All the other views always scale to your computer screen resolution. The idea of a mosaic is to generate an image for publication, and therefore when you use File/Save and File/Copy with the mosaic view the resolution is determined by the base resolution of your image, not the current resolution of your screen (to minimize interpolation). This often means that the saved mosaics often look a little different to the ones shown on screen, as they optimize the aspect ratio. This is a feature, not a defect.

Additional features are described in the release notes, but some of these are shown below. Specifically, if you drop a folder with several DICOM series onto the toolbar, you will get the option to open one series. MacOS users get an experimental dark mode. The tool panel now allows the user to select the line color and line thickness of lines (and you have script commands for this). Note that line colors are not allowed to be precisely the same color as the background, so if your background is pure white (255,255,255), then a white line will be shown as black (to enhance contrast). If you really wanted a white line in this case, you could set the line color to (255,255,254). The mosaics allow you to show renderings (`R`) and the orthogonal lines (`X`). These two scripts showcase some of these features

```
BEGIN
	RESETDEFAULTS;
	COLORBARVISIBLE(false);
	LOADIMAGE('mni152_2009bet');
	MOSAIC('A R 20 A R -20 S R -20; C R 0 CR -20 S R 20');
	OVERLAYLOAD('motor');
	OVERLAYMINMAX(1, 4, 4);
END.
```

```
BEGIN
	RESETDEFAULTS;
	COLORBARVISIBLE(false);
	LOADIMAGE('mni152_2009bet');
	OVERLAYLOAD('motor');
	OVERLAYMINMAX(1, -4, -4);
	CLIPAZIMUTHELEVATION(0.5, 90, 0);
	MOSAIC('V -0.2 H -0.2 A -24 -16 40 50; 60 70 S X R 20');
	XBARTHICK(3);
	XBARCOLOR(255, 255, 255);
END.
```

![dcmload](https://user-images.githubusercontent.com/8930807/38632451-cfa6ed8a-3d8a-11e8-81e1-a8a11bfd89d9.jpg)
![cross_lines](https://user-images.githubusercontent.com/8930807/38632476-dbc23340-3d8a-11e8-9b6f-2eb88ab3e221.jpg)
![render_mosaic](https://user-images.githubusercontent.com/8930807/38632485-e15f9f18-3d8a-11e8-9eeb-d49041718ced.jpg)

**Comment by mzunhammer** [comment]
Thank you! New version is looking great!
