### ISSUE TITLE
Updated Release on NITRC?

### ISSUE THREAD

**Issue by dowdlelt** [neurolabusc/MRIcroGL#23]
Hey folks, is there any timeline on when the pre-compiled version will be updated on NITRC? I did attempt a compile myself, but ran into a number of difficulties. Thanks for the excellent software, couldn't science nearly as well without it.

**Comment by neurolabusc** [comment]
You can download the latest compiled [pre-release](https://github.com/neurolabusc/MRIcroGL/releases) from Github - click on the releases button on the main page. If you have any issues, please report it here.

The next major release is waiting on a [Philips DTI validation dataset](https://github.com/rordenlab/dcm2niix/issues/182). I do not have access to Philips hardware, but @vuiiscci  has offered to provide a set shortly. Perhaps he can comment.

**Comment by dowdlelt** [comment]
Ack, my mistake - thanks for replying so quickly, not sure how I missed that! I think the latest release on there will work just perfectly for me. Thanks again for this and all the rest.
