### ISSUE TITLE
disorienting UI behavior

### ISSUE THREAD

**Issue by hanayik** [neurolabusc/MRIcroGL#25]
When you are viewing an image in multi-plane mode, and happen to click in an empty area in the left tool bar (even by accident), the display mode will automatically switch to "render". I discovered by accident. Not sure if intentional, but it was disorienting because I clicked on a button-less area and things happened.

**Comment by neurolabusc** [comment]
This is a feature - clicking on unused part of toolbar is a shortcut to go from 2D views to render view.
