### ISSUE TITLE
Mosaic text shows up inside mosaic brain

### ISSUE THREAD

**Issue by hanayik** [neurolabusc/MRIcroGL#28]
in mosaic view, the slice text shows up inside the brain. the user can turn it off, but when it's on, being inside the brain isn't ideal. I attempted to find where in the code this happens, but came up empty handed. 

<img width="1025" alt="screen shot 2018-06-01 at 5 26 04 pm" src="https://user-images.githubusercontent.com/5217720/40864874-a842589a-65c3-11e8-9865-9663e6fae080.png">

**Comment by neurolabusc** [comment]
Labels are only for quick display, the ability to have multiple overlapping rows and columns in the mosaic view makes automated label positioning unfeasible. Users are advised to use a vector art drawing program to add labels for publication. This is now reflected in the [documentation](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Mosaic_Views).
