### ISSUE TITLE
Genertation Python modules

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcroGL#30]
I am trying to get the new scripting features installed, but running:

```
lazbuild -B --lazarusdir="/usr/share/lazarus/" --pcp="with-packages" simplelaz.lpi
```

This seems to successfully compile and results in [this log](http://bpaste.net/show/0671c0874332), but will not produce any `"*.py*"` files I can place into my `$PYTHONPATH`. See the output of `tree` after running the aforementioned command, [here](http://bpaste.net/show/9a19aff2f19a).

Perhaps expectedly, `python -c 'import gl'`, gives me:

```
ModuleNotFoundError: No module named 'gl'
```

Am I misunderstanding how this is supposed to work, or has `lazbuild` omitted to build something?

**Comment by neurolabusc** [comment]
You will need to tell Surfice/MRIcroGL the location of your Python installation. It will attempt to find this when it starts, but this may not work for distributions I have not used like Gentoo. If nothing else, the Pascal scripting is always built into Surfice/MRIcroGL. You may need to edit the file ~/.mricrogl/MRIcroGL.ini and set "PyLib" to point to the location of your Python. Once this is done, you will be able to run Python scripts from the MRIcroGL/Surfice scripting window. All the functions are in-built and provide natively compiled performance. The next generation MRIcroGL 1.2 will further extend these features.

 I suggest you follow [these instructions](https://neurostars.org/t/getting-gifti-surface-data-into-python/2478/5).

**Comment by TheChymera** [comment]
Ah, I see.

The issue was more the uncommon usage method. I would echo @pjkohler's surprise that the Python functionality can only be used from within MRIcroGL or as an argument to the command. I had expected it to be importable in the Python interpreter (since that is how Python bindings, including for non-Python libraries, tend to work). My bad. Is there, however, any chance that MRIcroGL's excellent rendering functionality could be used directly from the interpreter in the foreseeable future?

**Comment by pjkohler** [comment]
I second the request above from @TheChymera.

**Comment by neurolabusc** [comment]
I think this usage is pretty typical of natively-compiled OpenGL tools, e.g. tools like Blender have similar functionality. For your use, perhaps you should consider [FSLeyes and Jupyter Notebook](https://users.fmrib.ox.ac.uk/~paulmc/fsleyes_userdoc/fsleyes_notebook.html). FSLeyes is a terrific tool that is primarily written in Python, with both the strengths and limitations that implies. Both tools are open source and you are free to develop and extend as you wish. I have limited resources and a lot of commitments. Personally, I think this is a case of horses for courses: I use FSLeyes when it is the right tool for my aims. Its hard to justify engineering effort when an excellent, actively developed open source tool with the desired features already exists.

**Comment by neurolabusc** [comment]
Closing this issue. If anyone wants to actively develop richer support, feel free to create a fork, submit pull requests and re-open this issue.
