### ISSUE TITLE
Need of a cyclic corolmap

### ISSUE THREAD

**Issue by seralouk** [neurolabusc/MRIcroGL#35]
Hi all,

I am using MRIcroGL in order to create some brain visualizations.

I have an activation map and I need to use a cyclic colormap such as the HSV colormap. however, such option is not available.

Any tip?

I also posted this here: https://www.nitrc.org/forum/forum.php?thread_id=11413&forum_id=4442

**Comment by neurolabusc** [comment]
You can create new color lookup tables with a text editor. The format is very simple. You describe the number of nodes, each node has an intensity associated with it (the [color index horizontal position](https://octave.sourceforge.io/octave/function/hsv.html)). Finally, each node has a red/green/blue/alpha value associated with it. Intensity and RGBA are values in the range 0..255. To make the colormap cyclic, just make the final node have the same color (red, green and blue values) as the first node. Save the text file with the extension ".clut" and place the file in MRIcroGL's ` /Resources/lut` folder (for MacOS, select the MRIcroGL application and `Show Package Contents` to see these folders). When you re-launch MRIcroGL it will include the new color table. Here is an example for the [HSV](https://octave.sourceforge.io/octave/function/hsv.html) color table:

```
[FLT]
min=0
max=0
[INT]
numnodes=7
[BYT]
nodeintensity0=0
nodeintensity1=43
nodeintensity2=85
nodeintensity3=128
nodeintensity4=170
nodeintensity5=213
nodeintensity6=255
[RGBA255]
nodergba0=255|0|0|0
nodergba1=255|255|0|14
nodergba2=0|255|0|28
nodergba3=0|255|255|43
nodergba4=0|0|255|57
nodergba5=255|0|255|71
nodergba6=255|0|0|85
```

When designing color maps, please be mindful of how people with color blindness will perceive your colors. Criticisms of the classic Matlab color maps and modern alternatives (such as the Viridis and Plasma schemes provided with MRIcroGL) are [here](https://elifesciences.org/labs/c2292989/jetfighter-towards-figure-accuracy-and-accessibility), [here](https://bids.github.io/colormap/) and [here](https://onlinelibrary.wiley.com/doi/pdf/10.1111/ejn.14430). @CPernet provides tools for controlling [luminance in color maps](https://github.com/CPernet/brain_colours).



![hsv2](https://user-images.githubusercontent.com/8930807/84887774-42134a00-b064-11ea-8158-6980fa14afe7.png)

**Comment by seralouk** [comment]
Amazing answer thank you a lot! i have now created my colormap successfully and MRIcroGL is able to recognize it. One last thing.

**Comment by mahirtazwar** [comment]
What would be the color table if I want to generate random colormap (similar to the random colormap in fsleyes, or how segmentations are loaded on ITK-SNAP)? In this case, each region of interest with a unique label will have a unique or repeated color (since I have more than 200+ ROIs).

**Comment by neurolabusc** [comment]
Set the intent_code of your [NIfTI header](https://brainder.org/2012/09/23/the-nifti-file-format/) to 1002 to specify [NIFTI_INTENT_LABEL](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h). This will use the same random color scheme as FSLeyes and use nearest neighbor interpolation (to solve the partial volume issue that a voxel that is a mixture of area 17 and area 19 should not be identified as area 18).

To see examples, choose any of the images listed under the File/AddAtlas menu item.

**Comment by neurolabusc** [comment]
You can always create your own `random` color schemes, just specify a lot of nodes for your color scheme each with a distinct color. For more details on color schemes, see the [NiiVue documentation](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md) which links to a [live demo that allows you to experiment with color schemes](https://niivue.github.io/niivue/features/colormaps.html).
