### ISSUE TITLE
How to convert the coronal scans into a nifti image?

### ISSUE THREAD

**Issue by chengjianhong** [neurolabusc/MRIcroGL#36]
Hi, 
When I use MRIcroGL to convert a coronal scan into a nifti image, I have a problem. I try two ways to do this by using MRIcroGL. The first is to save nifti images directly by "File-> Save NIFTI". The second is to save nifti images by the following command “dcm2niix.exe -f  'output_filename' -i y -l y -p y -x I y -v y -z y -o 'output_path' 'input_path' “.  Both of the above-generated results are different.  The image shape using the first way is  (X, Y, Z): 320 x 85 x 320, which is my desire. However, the image shape using the second way is (X, Y, Z): 320 x 320 x 85.  Because I will deal with a lot of coronal Dicom files, I want to use the second way for batch processing. But it will happen the above error. How to do this using the command?

Best wishes,
Jianhong Cheng

**Comment by neurolabusc** [comment]
You do not mention the version of MRIcroGL or the operating system. I am going to assume you are using the most recent [release](https://github.com/rordenlab/MRIcroGL12/releases). You should only supply one argument to -x, so in your sample above I would think you meant `dcm2niix.exe -f 'output_filename' -i y -l y -p y -x i -v y -z y -o 'output_path' 'input_path' `, where `-x i` specifies you do not want 3D acquisitions losslessly rotated to the axial plane.

 Remember, this only changes the order of the rows, columns and slices of image data saved to disk. The storm/qform always stores the transformation to world space. Therefore, an image saved as LPS (axial slices) and LSP (coronal slices) on disk should appear identically with a viewer that reads the spatial transform (like MRIcroGL). If your subsequent tool ignores the spatial transform, I would upgrade it to support this (if not, I would be worried it may not distinguish images that are left-right flipped).

**Comment by chengjianhong** [comment]
@neurolabusc
Hi, It still does not work using MRIcroGL 1.2.20200331 on windows 10.0.  I upload my test sample and results. flair.zip is coronal FLAIR Dicom files. Flair_firstway.nii.gz is generated by "File-> Save NIFTI", which is my desire. Flair_second_way.nii.gz is generated by your provided the command `dcm2niix.exe -f 'output_filename' -i y -l y -p y -x i -v y -z y -o 'output_path' 'input_path'`. But it still not the same as  Flair_firstway.nii.gz.

[flair.zip](https://github.com/neurolabusc/MRIcroGL/files/5474976/flair.zip)
[Flair_firstway.nii.gz](https://github.com/neurolabusc/MRIcroGL/files/5474977/Flair_firstway.nii.gz)
[Flair_second_way.nii.gz](https://github.com/neurolabusc/MRIcroGL/files/5474979/Flair_second_way.nii.gz)

**Comment by neurolabusc** [comment]
The `-x`argument will only rotate 3D acquisitions. Your FLAIR scan is a 2D sequence. dcm2niix preserves the slice orientation of 2D sequences, as required by slice timing tools. This 2D series was acquired as coronal slices and is saved as coronal slices. dcm2niix is designed to losslessly rotate images when it will not impact post processing. You can always use a simple script or tool to re-orient your images. For example, the [i2nii](https://github.com/rordenlab/i2nii) argument `-r y` will rotate images to match the NIfTI identity matrix (e.g. resliced to axial). 

However, be aware that these changes are lossless. Any tool that respects the sform should show an image identically before and after rotation. What tool are you using that makes you want to reslice your data?

```
>dcm2niix_stable -f 'output_filename' -i y -l y -p y -x i -v y -z y -o ./ ./
Chris Rorden's dcm2niiX version v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) Clang11.0.0 (64-bit MacOS)
Found 18 DICOM file(s)
...

>fslhd output_filename
filename	output_filename.nii.gz
sizeof_hdr	348
data_type	INT16
dim0		3
dim1		512
dim2		512
dim3		18
...
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	-0.448568 0.010242 -0.375193 117.267929 
sto_xyz:2	0.021857 -0.001620 -7.690826 57.850594 
sto_xyz:3	0.010309 0.449099 -0.019191 -104.825638 
sto_xyz:4	0.000000 0.000000 0.000000 1.000000 
sform_xorient	Right-to-Left
sform_yorient	Inferior-to-Superior
sform_zorient	Anterior-to-Posterior
```

**Comment by chengjianhong** [comment]
I want to do the following preprocessing: LPS, co-registered, and skull stripped after converting the nii image.  I find that the coronal FLAIR scans are executed by "File-> Save NIFTI", the generated images will be helpful for the above preprocessing.

**Comment by neurolabusc** [comment]
Great. Sounds like you have found a solution. If you want to automate this, you could use a tool like i2nii.
