### ISSUE TITLE
Incorporating cividis colorscheme

### ISSUE THREAD

**Issue by parekhpravesh** [neurolabusc/MRIcroGL#37]
Hello,

Nuñez et al (2018) [https://doi.org/10.1371/journal.pone.0199239)](url) introduced an optimized colormap that is more inclusive of people with color vision deficiency. Maybe this optimized version of _viridis_, named _cividis_ could be incorporated into MRIcroGL and SurfIce? 

I have added a clut file for cividis; I looked up the colors used in viridis and replaced them with the corresponding RGB from cividis. A naive version of clut with all 256 nodes (which is not practical) is also attached. I have changed the extension from .clut to .txt
[cividis.txt](https://github.com/neurolabusc/MRIcroGL/files/5688651/cividis.txt)
[cividis255.txt](https://github.com/neurolabusc/MRIcroGL/files/5688652/cividis255.txt)

A quick side-by-side comparison of viridis (left) and cividis (right) is below:

![Demo_Cividis](https://user-images.githubusercontent.com/8792123/102079761-4366d900-3e33-11eb-88b1-8a99370fe8ca.png)

Resources:
Details on clut format: [https://www.nitrc.org/forum/message.php?msg_id=26007](url)
Examples of cividis: [https://www.ncl.ucar.edu/Document/Graphics/ColorTables/cividis.shtml](url)
[https://github.com/marcosci/cividis](url)

**Comment by neurolabusc** [comment]
Thanks. Will be included with the next stable release of MRIcroGL and Surfice.
