### ISSUE TITLE
PyInt_fromLong and PyString_fromString

### ISSUE THREAD

**Issue by amirzolal** [neurolabusc/MRIcroGL#38]
Hello, 

these need to be replaced in order to compile on Ubuntu 20.04, I have replaced them with PyLong_fromLong and PyUnicode_fromString, compiled, but I do not know if it will have any consequences later. I don't know how to configure Lazarus to use Python 2.

**Comment by neurolabusc** [comment]
As noted in the README.md, MRIcroGL 1.0 is no longer actively maintained. Development has moved to [MRIcroGL 1.2](https://github.com/rordenlab/MRIcroGL12). That version using [Python27-for-Lazarus](https://github.com/neurolabusc/Python27-for-Lazarus) which supports legacy Python 2.7 as well as 3.x. This will work well with Ubuntu 20.04 (that is the distribution I use).
