### ISSUE TITLE
Save high-resolution images

### ISSUE THREAD

**Issue by lrq3000** [neurolabusc/MRIcroGL#9]
MRIcroGL can make really outstanding visualizations of the brain with a quite simple to use GUI, congratulations for the great work!

However, I can't find a way to save PNG/JPG images with a higher resolution than the window size on my screen (I looked in the GUI and in scripting). Would it be possible to add a "enlargement" option when saving, so that we can save the image at 2x/3x/5x resolution of window size?

**Comment by neurolabusc** [comment]
I assume you are using a relatively recent version of the software.

Choose File/Save or Edit/Copy to save or copy a bitmap. These images are created with higher quality than the screen rendering (so will look better than a screen shot). You can control the enlargement option by choosing "Preferences" and selecting the zoom factor. I would suggest x2 or x3 - unless you have very high resolution volumes a higher enlargement ratio will be contained by your voxel resolution.

The software actually generates these screenshots from a series of tiles, for example a x3 image will be created as 9 images (a 3x3 grid). The benefit of this method is that it works even if your graphics driver will not support contexts larger than your monitor. The disadvantage is that I require a integer expansion - you can not choose a x2.5 expansion.

For details see here:
http://www.mccauslandcenter.sc.edu/mricrogl/beta-features

**Comment by lrq3000** [comment]
Ah perfect, thanks a lot!

BTW, I used MRIcroGL for an internal art context around brain imagery, here are two of my entries :)

![tricky-issues-highres](https://cloud.githubusercontent.com/assets/1118942/22184215/8b7ec134-e0cd-11e6-8f1b-607b05c66bc4.jpg)
![serendipity-highres](https://cloud.githubusercontent.com/assets/1118942/22184216/8b81e72e-e0cd-11e6-95f7-8977ce056161.jpg)

Keep up your great work!

**Comment by neurolabusc** [comment]
These are very pretty. Do you have a web page or scripts that describe your technique?

Also, do take a look at my Surf Ice software. While MRIcroGL is a volume renderer, Surf Ice is a surface renderer. You find that one style of software is more suitable for your artistic goals.

**Comment by lrq3000** [comment]
Ah great, I didn't know how Surf Ice fitted in the family of software you made! I'll try it out next time I need a surface rendering :)

About the images, no I don't have a webpage, but both were generated using MRIcroGL with the provided brodmann.nii.gz template:
* Serendipity was made using only MRIcroGL: shader "simple", boundExp > 0, then I played with the view and parameters to make it look a bit more pretty. I also removed parasites (ie, black dots) using [GIMP](https://www.gimp.org/).
* TrickyIssues is also brodmann template with shader "simple" but boundExp = 0. Then I used GIMP to use the [rabbit-duck illusion](https://en.wikipedia.org/wiki/Rabbit%E2%80%93duck_illusion) as a mask to the brain image.

BTW, both images are under BSD License / Creative Commons BY at the choice of user.

**Comment by neurolabusc** [comment]
You can get rid of the black dots with a minor modification of the shader (put the attached file into your "shaders" folder - if you use macOS you need to select the application and choose "Show package contents" to see the shader folder):

[simpleExp.txt](https://github.com/neurolabusc/MRIcroGL/files/723813/simpleExp.txt)

**Comment by lrq3000** [comment]
Thank you very much @neurolabusc for the fixed shader :-)

Here are the updated pictures in high resolution, and with just a bit of finition with GIMP and RawTherapee. Feel free to use them, they are under creative commons BY 3.0 or BSD-2-Clause as you prefer :-) (note that diversity-flows and tricky-issues are using two images from Escher, which are in the public domain now).

![serendipity-highres_2](https://user-images.githubusercontent.com/1118942/34781430-184e37ca-f626-11e7-9a63-766fad7918a7.jpg)

![diversity-flows-highres_3](https://user-images.githubusercontent.com/1118942/34784021-67492158-f62d-11e7-9f72-b1bc93ee39ca.jpg)

![tricky-issues-highres_2](https://user-images.githubusercontent.com/1118942/34784027-6b363be8-f62d-11e7-920d-ece342804529.jpg)

**Comment by neurolabusc** [comment]
Nice

**Comment by neuronflow** [comment]
@neurolabusc is there a way to control the zoom level in scripting mode? I am using MRIcroGL to render images on a server and the resulting renderings all have a bit too much black space around them.
![scintillating-unequal-meeting_crabby-sordid-revolution_rota090](https://user-images.githubusercontent.com/7048826/52400218-cf34af00-2abe-11e9-9ec1-956c33de0b65.png)

**Comment by neuronflow** [comment]
Managed to solve it with the following scripting params :)
CAMERADISTANCE(0.6);
BMPZOOM(1);

I love your software, thank you!
